modLoader="javafml"
loaderVersion="[42,)"
license="Unlicense"

[[mods]]
modId="testapimod"
version="${file.jarVersion}"
displayName="Test API Mod"
# updateJSONURL=""
# displayURL=""
# logoFile=""
credits=""
authors=""
description=""

[[dependencies.testapimod]]
    modId="forge"
    mandatory=true
    versionRange="[42,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.testapimod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.1,1.20)"
    ordering="NONE"
    side="BOTH"
